import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "ar" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
  isRTL: boolean;
}

const translations = {
  ar: {
    // App
    "app.name": "شحنلي",
    "app.welcome": "مرحباً بك في شحنلي",
    "app.subtitle": "منصة الشحن الذكية للجميع",

    // Navigation
    "nav.dashboard": "لوحة التحكم",
    "nav.createShipment": "إنشاء شحنة",
    "nav.shipments": "الشحنات",
    "nav.contacts": "العملاء",
    "nav.balance": "الرصيد",
    "nav.reports": "التقارير",
    "nav.settings": "الإعدادات",
    "nav.logout": "تسجيل الخروج",
    "nav.profile": "الملف الشخصي",

    // Auth
    "auth.signIn": "تسجيل الدخول",
    "auth.signUp": "إنشاء حساب",
    "auth.createNewAccount": "إنشاء حساب جديد",
    "auth.createAccount": "إنشاء الحساب",
    "auth.backToLogin": "العودة إلى تسجيل الدخول",
    "auth.joinPlatform": "انضم إلى منصة شحنلي اليوم",
    "auth.email": "البريد الإلكتروني",
    "auth.emailAddress": "عنوان البريد الإلكتروني",
    "auth.password": "كلمة المرور",
    "auth.confirmPassword": "تأكيد كلمة المرور",
    "auth.firstName": "الاسم الأول",
    "auth.lastName": "الاسم الأخير",
    "auth.phone": "رقم الهاتف",
    "auth.phoneNumber": "رقم الهاتف",
    "auth.accountType": "نوع الحساب",
    "auth.individual": "فرد",
    "auth.merchant": "تاجر",
    "auth.companyName": "اسم الشركة",
    "auth.commercialRegister": "رقم السجل التجاري",
    "auth.country": "البلد",
    "auth.province": "المحافظة",
    "auth.city": "المدينة",
    "auth.street": "الشارع",
    "auth.rememberMe": "تذكرني",
    "auth.forgotPassword": "هل نسيت كلمة المرور؟",
    "auth.dontHaveAccount": "ليس لديك حساب؟",
    "auth.alreadyHaveAccount": "لديك حساب بالفعل؟",
    "auth.hasAccount": "لديك حساب بالفعل؟",
    "auth.noAccount": "ليس لديك حساب؟",
    "auth.signInHere": "سجل دخولك هنا",
    "auth.signUpHere": "أنشئ حساباً هنا",
    "auth.welcome": "مرحباً بك",
    "auth.signInSubtitle": "سجل دخولك للوصول إلى حسابك",
    "auth.signUpSubtitle": "أنشئ حساباً جديداً للبدء",
    "auth.creatingAccount": "جاري إنشاء الحساب...",
    "auth.signingIn": "جاري تسجيل الدخول...",
    "auth.loginSuccess": "تم تسجيل الدخول بنجاح",
    "auth.loginError": "فشل في تسجيل الدخول",
    "auth.logoutSuccess": "تم تسجيل الخروج بنجاح",

    // Forgot Password - Enhanced Arabic translations
    "auth.resetPassword": "إعادة تعيين كلمة المرور",
    "auth.linkSent": "تم إرسال الرابط",
    "auth.enterEmail": "يرجى إدخال البريد الإلكتروني",
    "auth.enterEmailForReset":
      "أدخل عنوان بريدك الإلكتروني لإعادة تعيين كلمة المرور",
    "auth.checkEmailInstructions":
      "تحقق من صندوق البريد الإلكتروني الخاص بك واتبع التعليمات لإعادة تعيين كلمة المرور",
    "auth.sendResetLink": "إرسال رابط إعادة التعيين",
    "auth.sending": "جاري الإرسال...",
    "auth.resetLinkSent": "تم إرسال رابط إعادة التعيين",
    "auth.resetLinkSentTo": "تم إرسال رابط إعادة تعيين كلمة المرور إلى:",
    "auth.didntReceiveEmail": "لم تستلم البريد الإلكتروني؟",
    "auth.sendAgain": "إرسال مرة أخرى",
    "auth.sendingResetLink": "جاري إرسال رابط إعادة التعيين...",
    "auth.linkSentSuccess": "تم إرسال الرابط بنجاح",
    "auth.linkSendFailed": "فشل في إرسال الرابط",
    "auth.resetPasswordError": "حدث خطأ في إعادة تعيين كلمة المرور",

    // Profile
    "profile.title": "الملف الشخصي",
    "profile.personalInfo": "المعلومات الشخصية",
    "profile.fullName": "الاسم الكامل",
    "profile.company": "الشركة",
    "profile.website": "الموقع الإلكتروني",
    "profile.bio": "نبذة تعريفية",
    "profile.memberSince": "عضو منذ",
    "profile.saveChanges": "حفظ التغييرات",
    "profile.profileSaved": "تم حفظ الملف الشخصي بنجاح",
    "profile.languageChanged": "تم تغيير اللغة بنجاح",
    "profile.accountTypeChanged": "تم تغيير نوع الحساب بنجاح",

    // Profile - Enhanced Account Type
    "profile.selectAccountTypeDesc": "اختر نوع الحساب المناسب لاستخدامك",
    "profile.individualDesc": "للاستخدام الشخصي والأفراد",
    "profile.merchantDesc": "للشركات والتجار",
    "profile.personalAccount": "حساب شخصي",
    "profile.verified": "موثق",
    "profile.easySetup": "إعداد سهل",
    "profile.quickStart": "بداية سريعة",
    "profile.businessFeatures": "مميزات تجارية",
    "profile.bulkShipping": "شحن بالجملة",

    // Profile - Notifications
    "profile.notifications": "الإشعارات",
    "profile.emailNotifications": "إشعارات البريد الإلكتروني",
    "profile.emailNotificationsDesc": "تلقي إشعارات عبر البريد الإلكتروني",
    "profile.smsNotifications": "إشعارات الرسائل النصية",
    "profile.smsNotificationsDesc": "تلقي إشعارات عبر الرسائل النصية",
    "profile.pushNotifications": "الإشعارات الفورية",
    "profile.pushNotificationsDesc": "تلقي إشعارات فورية على المتصفح",
    "profile.shipmentUpdates": "تحديثات الشحنات",
    "profile.shipmentUpdatesDesc": "تلقي إشعارات حول تحديثات الشحنات",
    "profile.promotions": "العروض الترويجية",
    "profile.promotionsDesc": "تلقي إشعارات حول العروض والخصومات",

    // Profile - Security
    "profile.security": "الأمان",
    "profile.twoFactorAuth": "المصادقة الثنائية",
    "profile.twoFactorAuthDesc": "تفعيل المصادقة الثنائية لحماية إضافية",
    "profile.loginAlerts": "تنبيهات تسجيل الدخول",
    "profile.loginAlertsDesc": "تلقي تنبيهات عند تسجيل دخول جديد",
    "profile.sessionTimeout": "انتهاء صلاحية الجلسة",
    "profile.timeout15": "15 دقيقة",
    "profile.timeout30": "30 دقيقة",
    "profile.timeout60": "60 دقيقة",
    "profile.timeout120": "120 دقيقة",
    "profile.changePassword": "تغيير كلمة المرور",
    "profile.currentPassword": "كلمة المرور الحالية",
    "profile.newPassword": "كلمة المرور الجديدة",
    "profile.confirmNewPassword": "تأكيد كلمة المرور الجديدة",
    "profile.updatePassword": "تحديث كلمة المرور",

    // Profile - Preferences
    "profile.preferences": "التفضيلات",
    "profile.language": "اللغة",
    "profile.currency": "العملة",
    "profile.dangerZone": "المنطقة الخطرة",
    "profile.deleteAccount": "حذف الحساب",

    // Features
    "features.easyManagement": "إدارة سهلة للشحنات",
    "features.realTimeTracking": "تتبع فوري للطرود",
    "features.multiLanguage": "دعم متعدد اللغات",

    // Terms
    "terms.agreeToTerms": "أوافق على",
    "terms.termsAndConditions": "الشروط والأحكام",
    "terms.and": "و",
    "terms.privacyPolicy": "سياسة الخصوصية",

    // Dashboard
    "dashboard.welcome": "مرحباً بك",
    "dashboard.totalShipments": "إجمالي الشحنات",
    "dashboard.pendingShipments": "الشحنات المعلقة",
    "dashboard.deliveredShipments": "الشحنات المسلمة",
    "dashboard.totalRevenue": "إجمالي الإيرادات",
    "dashboard.recentShipments": "الشحنات الأخيرة",
    "dashboard.quickActions": "الإجراءات السريعة",
    "dashboard.createShipment": "إنشاء شحنة",
    "dashboard.viewAllShipments": "عرض جميع الشحنات",
    "dashboard.manageContacts": "إدارة العملاء",
    "dashboard.viewReports": "عرض التقارير",
    "dashboard.viewAll": "عرض الكل",
    "dashboard.noShipments": "لا توجد شحنات",
    "dashboard.noShipmentsDesc": "لم تقم بإنشاء أي شحنات بعد",
    "dashboard.walletBalance": "رصيد المحفظة",
    "dashboard.chargeWallet": "شحن المحفظة",
    "dashboard.totalShipmentsCount": "إجمالي الشحنات",
    "dashboard.pendingCount": "الشحنات المعلقة",
    "dashboard.deliveredCount": "الشحنات المسلمة",
    "dashboard.monthlyGrowth": "نمو شهري",
    "dashboard.recentShipmentsTitle": "الشحنات الأخيرة",
    "dashboard.quickActionsTitle": "الإجراءات السريعة",
    "dashboard.createNewShipment": "إنشاء شحنة جديدة",
    "dashboard.startNewShipment": "ابدأ شحنة جديدة الآن",
    "dashboard.viewAllShipmentsDesc": "تتبع وإدارة جميع شحناتك",
    "dashboard.sendersReceivers": "إدارة العملاء",

    // Shipments
    "shipments.title": "الشحنات",
    "shipments.subtitle": "إدارة وتتبع جميع شحناتك",
    "shipments.createShipment": "إنشاء شحنة",
    "shipments.searchShipments": "البحث في الشحنات...",
    "shipments.searchPlaceholder":
      "البحث برقم التتبع أو اسم المرسل أو المستقبل...",
    "shipments.filterByStatus": "تصفية حسب الحالة",
    "shipments.allStatuses": "جميع الحالات",
    "shipments.pending": "معلقة",
    "shipments.inTransit": "في الطريق",
    "shipments.delivered": "تم التسليم",
    "shipments.cancelled": "ملغية",
    "shipments.returned": "مرتجعة",
    "shipments.noShipments": "لا توجد شحنات",
    "shipments.noShipmentsFound":
      "لم يتم العثور على شحنات مطابقة لمعايير البحث",
    "shipments.noMatchingShipments": "لا توجد شحنات مطابقة لمعايير البحث",
    "shipments.trackingNumber": "رقم التتبع",
    "shipments.sender": "المرسل",
    "shipments.receiver": "المستقبل",
    "shipments.status": "الحالة",
    "shipments.amount": "المبلغ",
    "shipments.date": "التاريخ",
    "shipments.actions": "الإجراءات",
    "shipments.view": "عرض",
    "shipments.edit": "تعديل",
    "shipments.track": "تتبع",
    "shipments.delete": "حذف",
    "shipments.details": "تفاصيل الشحنة",
    "shipments.shipmentDetails": "تفاصيل الشحنة",
    "shipments.close": "إغلاق",
    "shipments.fromTo": "من {from} إلى {to}",
    "shipments.printBill": "طباعة الفاتورة",
    "shipments.printShippingBill": "طباعة فاتورة الشحن",
    "shipments.shippingBill": "فاتورة الشحن",
    "shipments.choosePrintMethod": "اختر طريقة الطباعة",
    "shipments.downloadPDF": "تحميل ملف PDF",
    "shipments.printWindowOpened": "تم فتح نافذة الطباعة",
    "shipments.pdfFeatureComingSoon": "ميزة تحميل PDF قريباً",
    "shipments.cancelShipment": "إلغاء الشحنة",
    "shipments.cancelRequest": "طلب إلغاء الشحنة",
    "shipments.confirmCancel": "هل أنت متأكد من إلغاء هذه الشحنة؟",
    "shipments.cancelWarning":
      "لا يمكن التراجع عن هذا الإجراء. سيتم إلغاء الشحنة نهائياً.",
    "shipments.cancelReason": "سبب الإلغاء",
    "shipments.cancelReasonPlaceholder": "يرجى توضيح سبب إلغاء الشحنة...",
    "shipments.enterCancelReason": "يرجى إدخال سبب الإلغاء",
    "shipments.goBack": "العودة",
    "shipments.confirmCancelButton": "تأكيد الإلغاء",
    "shipments.cancelRequestSent": "تم إرسال طلب إلغاء الشحنة {trackingNumber}",
    "shipments.cannotCancelApproved": "لا يمكن إلغاء الشحنات المعتمدة",
    "shipments.createdDate": "تاريخ الإنشاء",
    "shipments.estimatedDelivery": "التسليم المتوقع",

    // Status translations
    "status.pending": "معلقة",
    "status.in-transit": "في الطريق",
    "status.delivered": "تم التسليم",
    "status.cancelled": "ملغية",
    "status.returned": "مرتجعة",

    // Create Shipment
    "createShipment.title": "إنشاء شحنة جديدة",
    "createShipment.subtitle": "املأ التفاصيل أدناه لإنشاء شحنة جديدة",
    "createShipment.senderInfo": "معلومات المرسل",
    "createShipment.receiverInfo": "معلومات المستقبل",
    "createShipment.shipmentDetails": "تفاصيل الشحنة",
    "createShipment.pricing": "التسعير",
    "createShipment.selectFromContacts": "اختيار من العملاء",
    "createShipment.addNewContact": "عميل جديد",
    "createShipment.selectContact": "اختيار مرسل / مستلم",
    "createShipment.searchContacts": "البحث في العملاء...",
    "createShipment.noContacts": "لا توجد مرسلين / مستلمين",
    "createShipment.createShipment": "إنشاء الشحنة",
    "createShipment.success": "تم إنشاء الشحنة بنجاح",
    "createShipment.error": "فشل في إنشاء الشحنة",

    // Shipment Creation Steps
    "shipment.title": "إنشاء شحنة جديدة",
    "shipment.step1.title": "نوع الشحن",
    "shipment.step5.title": "الشحن والدفع",
    "shipment.reviewTitle": "مراجعة الشحنة",
    "shipment.selectShippingType": "اختر نوع الشحن",
    "shipment.selectShippingTypeDesc": "حدد ما إذا كانت الشحنة محلية أم دولية",
    "shipment.local": "شحن محلي",
    "shipment.localDesc": "شحن داخل سوريا فقط",
    "shipment.international": "شحن دولي",
    "shipment.internationalDesc": "شحن إلى دول أخرى",
    "shipment.companiesAvailable": "شركة متاحة",
    "shipment.localOnly": "الشحن المحلي فقط",
    "shipment.shippingCompany": "شركة الشحن",
    "shipment.supportsAllCountries": "تدعم جميع البلدان المحددة",
    "shipment.paymentMethod": "طريقة الدفع",
    "shipment.wallet": "المحفظة",
    "shipment.cashOnDelivery": "الدفع عند الاستلام",
    "shipment.cod": "الدفع عند الاستلام",
    "shipment.additionalNotes": "ملاحظات إضافية",
    "shipment.enterNotes": "أدخل أي ملاحظات إضافية...",
    "shipment.totalCostFor": "التكلفة الإجمالية لـ {count} مستقبل",
    "shipment.totalCost": "التكلفة الإجمالية",
    "shipment.reviewDetails": "مراجعة تفاصيل الشحنة",
    "shipment.reviewDesc": "تأكد من صحة جميع المعلومات قبل إنشاء الشحنة",
    "shipment.shippingInfo": "معلومات الشحن",
    "shipment.shippingType": "نوع الشحن",
    "shipment.costSummary": "ملخص التكلفة",
    "shipment.confirmCreate": "تأكيد إنشاء الشحنة",
    "shipment.previous": "السابق",
    "shipment.next": "التالي",
    "shipment.reviewShipment": "مراجعة الشحنة",
    "shipment.create": "إنشاء الشحنة",
    "shipment.creating": "جاري إنشاء الشحنة...",
    "shipment.createSuccess": "تم إنشاء الشحنة بنجاح",
    "shipment.createError": "فشل في إنشاء الشحنة",
    "shipment.notes": "الملاحظات",

    // Contacts
    "contacts.title": "العملاء",
    "contacts.subtitle": "إدارة المرسلين والمستقبلين",
    "contacts.addContact": "عميل جديد",
    "contacts.searchContacts": "البحث في العملاء...",
    "contacts.filterByType": "تصفية حسب النوع",
    "contacts.allTypes": "جميع الأنواع",
    "contacts.sender": "مرسل",
    "contacts.receiver": "مستقبل",
    "contacts.both": "كلاهما",
    "contacts.type": "النوع",
    "contacts.contact": "مرسل / مستلم",
    "contacts.noContacts": "لا توجد مرسلين / مستلمين",
    "contacts.noMatchingContacts": "لا توجد مرسلين / مستلمين مطابقة",
    "contacts.addContactDesc": "عميل جديد لاستخدامه في الشحنات",
    "contacts.editContact": "تعديل معلومات العميل",
    "contacts.editContactDesc": "تعديل معلومات العميل",
    "contacts.deleteSuccess": "تم حذف العميل بنجاح",
    "contacts.addSuccess": "تم إضافة العميل بنجاح",
    "contacts.updateSuccess": "تم تحديث العميل بنجاح",
    "contacts.locationSet": "تم تحديد الموقع",

    // Client Types
    "client.type": "نوع العميل",
    "client.individual": "فرد",
    "client.merchant": "تاجر",
    "client.filterByType": "تصفية حسب نوع العميل",
    "client.allTypes": "جميع الأنواع",

    // Company
    "company.name": "اسم الشركة",
    "company.enterName": "أدخل اسم الشركة",
    "company.documents": "وثائق الشركة",
    "company.uploadDocuments": "رفع وثائق الشركة",
    "company.documentsDesc":
      "PDF, JPG, PNG, DOC, DOCX - حد أقصى 5 ميجابايت لكل ملف",
    "company.chooseFiles": "اختيار الملفات",
    "company.uploadedFiles": "الملفات المرفوعة",
    "company.filesUploaded": "ملف مرفوع",

    // Balance
    "balance.title": "الرصيد",
    "balance.subtitle": "إدارة رصيد محفظتك وتاريخ المعاملات",
    "balance.usdBalance": "الرصيد بالدولار الأمريكي",
    "balance.sypBalance": "الرصيد بالليرة السورية",
    "balance.availableBalance": "الرصيد المتاح",
    "balance.chargeWallet": "شحن المحفظة",
    "balance.amount": "المبلغ",
    "balance.currency": "العملة",
    "balance.paymentMethod": "طريقة الدفع",
    "balance.bankTransfer": "تحويل بنكي",
    "balance.bankTransferDesc": "تحويل من حسابك البنكي",
    "balance.shamCash": "شام كاش",
    "balance.shamCashDesc": "دفع عبر شام كاش",
    "balance.syriatelCash": "سيرياتيل كاش",
    "balance.syriatelCashDesc": "دفع عبر سيرياتيل كاش",
    "balance.mtnCash": "إم تي إن كاش",
    "balance.mtnCashDesc": "دفع عبر إم تي إن كاش",
    "balance.transferReason": "سبب التحويل",
    "balance.transferReasonPlaceholder": "اختياري - سبب شحن المحفظة",
    "balance.chargeNow": "شحن الآن",
    "balance.transactionHistory": "تاريخ المعاملات",
    "balance.completed": "مكتمل",
    "balance.pending": "معلق",
    "balance.enterValidAmount": "يرجى إدخال مبلغ صحيح",
    "balance.chargeSuccess": "تم شحن المحفظة بنجاح بمبلغ {amount} {currency}",
    "balance.chargeError": "فشل في شحن المحفظة",
    "balance.charging": "جاري شحن المحفظة...",

    // Balance Search and Filter
    "balance.searchTransactions": "البحث في المعاملات...",
    "balance.searchPlaceholder": "البحث بالمبلغ أو طريقة الدفع أو الوصف...",
    "balance.filterByType": "تصفية حسب النوع",
    "balance.allTypes": "جميع الأنواع",
    "balance.charge": "شحن",
    "balance.withdraw": "سحب",
    "balance.payment": "دفع",
    "balance.filterByCurrency": "تصفية حسب العملة",
    "balance.allCurrencies": "جميع العملات",
    "balance.filterByStatus": "تصفية حسب الحالة",
    "balance.allStatuses": "جميع الحالات",
    "balance.noTransactionsFound": "لم يتم العثور على معاملات مطابقة",
    "balance.clearFilters": "مسح الفلاتر",

    // Withdraw Balance
    "balance.withdrawBalance": "سحب الرصيد",
    "balance.withdrawBalanceDesc":
      "اطلب سحب رصيدك من شحنات الدفع عند الاستلام المسلمة",
    "balance.availableForWithdraw": "المتاح للسحب",
    "balance.availableFromCOD": "المتاح من شحنات الدفع عند الاستلام",
    "balance.requestWithdraw": "طلب سحب الرصيد",
    "balance.withdrawAmount": "مبلغ السحب",
    "balance.withdrawMethod": "طريقة السحب",
    "balance.accountDetails": "تفاصيل الحساب",
    "balance.bankAccountPlaceholder": "رقم الحساب البنكي أو الآيبان",
    "balance.mobileNumberPlaceholder": "رقم الهاتف المحمول",
    "balance.notes": "ملاحظات",
    "balance.withdrawNotesPlaceholder": "ملاحظات إضافية (اختياري)",
    "balance.submitRequest": "إرسال الطلب",
    "balance.withdrawRequests": "طلبات السحب",
    "balance.noWithdrawRequests": "لا توجد طلبات سحب",
    "balance.withdrawPending": "معلق",
    "balance.withdrawApproved": "تمت الموافقة",
    "balance.withdrawRejected": "مرفوض",
    "balance.withdrawCompleted": "مكتمل",
    "balance.requestDate": "تاريخ الطلب",
    "balance.processedDate": "تاريخ المعالجة",
    "balance.withdrawRequestDesc":
      "يمكنك سحب رصيدك من شحنات الدفع عند الاستلام التي تم تسليمها بنجاح",
    "balance.withdrawAmountExceeds":
      "المبلغ المطلوب يتجاوز الرصيد المتاح للسحب",
    "balance.enterAccountDetails": "يرجى إدخال تفاصيل الحساب",
    "balance.withdrawRequestSuccess": "تم إرسال طلب السحب بنجاح",
    "balance.withdrawError": "فشل في إرسال طلب السحب",
    "balance.submittingRequest": "جاري إرسال الطلب...",
    withdrawal: " سحب",

    // Additional Balance translations
    "balance.wallet": "المحفظة",
    "balance.walletCharge": "شحن المحفظة",
    "balance.shipmentPayment": "دفع شحنة {shipmentId}",
    "balance.withdrawFromCOD": "طلب سحب من شحنات الدفع عند الاستلام",
    "balance.withdrawFromCODShipments": "سحب رصيد من شحنات الدفع عند الاستلام",
    "balance.bankAccountMasked": "حساب بنكي: ****1234",
    "balance.mobileNumberMasked": "هاتف: +963991234567",
    deposit: "إيداع",
    withdraw: "سحب",
    depositFunds: "إيداع أموال",
    withdrawFunds: "سحب أموال",
    depositDescription: "قم بإيداع الأموال إلى حسابك لاستخدامها في الشحن",
    withdrawDescription: "قم بسحب الأموال من حسابك إلى وسيلة الدفع المفضلة",
    currency: "العملة",
    amount: "المبلغ",
    paymentMethod: "وسيلة الدفع",
    withdrawMethod: "وسيلة السحب",
    selectPaymentMethod: "اختر وسيلة الدفع",
    selectWithdrawMethod: "اختر وسيلة السحب",
    confirmDeposit: "تأكيد الإيداع",
    confirmWithdraw: "تأكيد السحب",
    cancel: "إلغاء",
    localBalance: "الرصيد المحلي",
    internationalBalance: "الرصيد الدولي",
    syrianPoundForLocalRecharge: "الليرة السورية - للشحن المحلي",
    usDollarForInternationalRecharge: "الدولار الأمريكي - للشحن الدولي",
    syrianPoundSymbol: "ل.س",
    dollarSymbol: "$",
    syrianPoundWithCode: "الليرة السورية (SYP)",
    usDollarWithCode: "الدولار الأمريكي (USD)",
    pleaseEnterValidAmount: "الرجاء إدخال مبلغ صحيح",
    pleaseSelectPaymentMethod: "الرجاء اختيار وسيلة الدفع",
    pleaseSelectWithdrawMethod: "الرجاء اختيار وسيلة السحب",
    minimumDepositAmount: "الحد الأدنى للإيداع",
    maximumDepositAmount: "الحد الأقصى للإيداع",
    minimumWithdrawAmount: "الحد الأدنى للسحب",
    insufficientBalance: "الرصيد غير كافي",
    depositRequestSubmitted: "تم إرسال طلب الإيداع بنجاح",
    withdrawalRequestSubmitted: "تم إرسال طلب السحب بنجاح",
    creditCard: "بطاقة ائتمان",
    bankTransfer: "حوالة بنكية",
    mobileWallet: "محفظة إلكترونية",
    completed: "مكتمل",
    pending: "قيد الانتظار",
    failed: "فاشل",
    transactionHistory: "سجل المعاملات",
    recentTransactions: "آخر المعاملات",
    transactionsCount: "{{filtered}} من {{total}} معاملة",
    searchTransactionsPlaceholder:
      "ابحث برقم المرجع، الطريقة، التاريخ، أو المبلغ...",
    transactionType: "نوع المعاملة",
    all: "الكل",
    syrianPound: "الليرة السورية",
    usDollar: "الدولار الأمريكي",
    clearFilters: "مسح الفلاتر",
    noMatchingTransactions: "لا توجد معاملات تطابق معايير البحث",
    transactionDetails: "تفاصيل المعاملة",
    type: "النوع",
    status: "الحالة",
    method: "الطريقة",
    date: "التاريخ",
    reference: "رقم المرجع",
    notes: "ملاحظات",
    optional: "اختياري",
    withdrawNotesPlaceholder: "أي ملاحظات إضافية حول عملية السحب (اختياري)",
    close: "إغلاق",
    importantNotice: "ملاحظة هامة",
    balanceNotice: "يرجى ملاحظة الفرق بين الرصيدين وكيفية استخدام كل منهما:",
    localBalanceDescription:
      "الرصيد بالليرة السورية (SYP) يستخدم للشحن المحلي داخل سوريا",
    internationalBalanceDescription:
      "الرصيد بالدولار الأمريكي (USD) يستخدم للشحن الدولي",
    minimum: "الحد الأدنى",
    maximum: "الحد الأقصى",
    availableBalance: "الرصيد المتاح",
    urgentWithdrawalRequest: "طلب سحب عاجل",
    insufficientVerification: "التحقق غير كافي",
    pleaseCompleteVerification:
      "يرجى إكمال عملية التحقق لزيادة حد السحب الخاص بك.",
    verifyNow: "تحقق الآن",

    "balance.Local balance": "الرصيد المحلي",
    "balance.International balance": "الرصيد الدولي",
    "balance.SYP.currency": " الليرة السورية - للشحن المحلي",
    "balance.USD.currency": " الدولار الأمريكي - للشحن الدولي",

    // Client
    "sender.title": "المرسل",
    "sender.name": "الاسم",
    "sender.phone": "رقم الهاتف",
    "sender.email": "البريد الإلكتروني",
    "sender.country": "البلد",
    "sender.state": "المحافظة",
    "sender.city": "المدينة",
    "sender.street": "الشارع",
    "sender.address": "العنوان",
    "sender.detailedAddress": "العنوان التفصيلي",
    "sender.enterName": "أدخل الاسم",
    "sender.enterPhone": "أدخل رقم الهاتف",
    "sender.enterEmail": "أدخل البريد الإلكتروني",
    "sender.enterStreet": "أدخل الشارع",
    "sender.enterDetailedAddress": "أدخل العنوان التفصيلي",
    "sender.selectLocationOnMap": "اختيار الموقع على الخريطة",
    "sender.clickToSelectLocation": "انقر لاختيار موقع",
    "sender.interactiveMap": "خريطة تفاعلية",
    "sender.clickToSelect": "انقر على الخريطة لاختيار الموقع",
    "sender.selectThisLocation": "اختيار هذا الموقع",
    "sender.locationSelected": "تم اختيار الموقع",
    "sender.selectFromContacts": "اختيار من العملاء",
    "sender.selectOrEnterNew": "اختر من العملاء أو أدخل جديد",

    // Receiver
    "receiver.title": "المستقبل",
    "receiver.titlePlural": "المستقبلون",
    "receiver.number": "المستقبل رقم {number}",
    "receiver.count": "عدد المستقبلين",
    "receiver.enterName": "أدخل اسم المستقبل",
    "receiver.enterDetailedAddress": "أدخل العنوان التفصيلي للمستقبل",
    "receiver.selectOrEnterNew": "اختر من العملاء أو أدخل جديد",
    "receiver.locationSelected": "تم اختيار موقع المستقبل",

    // Package
    "package.title": "الطرد",
    "package.type": "نوع الطرد",
    "package.selectType": "اختر نوع الطرد",
    "package.documents": "وثائق",
    "package.electronics": "إلكترونيات",
    "package.clothing": "ملابس",
    "package.books": "كتب",
    "package.gifts": "هدايا",
    "package.food": "طعام",
    "package.other": "أخرى",
    "package.weight": "الوزن",
    "package.length": "الطول",
    "package.width": "العرض",
    "package.height": "الارتفاع",
    "package.dimensions": "الأبعاد",
    "package.description": "وصف المحتوى",
    "package.enterDescription": "أدخل وصف محتوى الطرد",
    "package.value": "قيمة الطرد",
    "package.fragile": "قابل للكسر",

    // Payment
    "payment.cod.desc": "سيتم تحصيل المبلغ عند التسليم",

    // Currency
    "currency.usd": "دولار أمريكي",
    "currency.syp": "ل.س",
    "currency.selectCurrency": "اختر العملة",

    // Countries
    "common.syria": "سوريا",
    "common.sy": "سوريا",
    "common.lb": "لبنان",
    "common.jo": "الأردن",

    // Common
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.edit": "تعديل",
    "common.delete": "حذف",
    "common.view": "عرض",
    "common.search": "بحث",
    "common.filter": "تصفية",
    "common.actions": "الإجراءات",
    "common.status": "الحالة",
    "common.date": "التاريخ",
    "common.amount": "المبلغ",
    "common.total": "الإجمالي",
    "common.loading": "جاري التحميل...",
    "common.error": "خطأ",
    "common.success": "نجح",
    "common.warning": "تحذير",
    "common.info": "معلومات",
    "common.confirm": "تأكيد",
    "common.yes": "نعم",
    "common.no": "لا",
    "common.close": "إغلاق",
    "common.selectCountry": "اختر البلد",
    "common.selectState": "اختر المحافظة",
    "common.selectCity": "اختر المدينة",
    "common.noResults": "لا توجد نتائج",
    "common.required": "*",
    "common.optional": "اختياري",
    "common.addReceiver": "إضافة مستقبل",
    "common.confirmDeleteContact": "هل انت متأكد من حذف العميل",
    "common.cannotReverseAction": "لا يمكن التراجع عن هذا الإجراء",

    // Messages
    "msg.fillRequired": "يرجى ملء جميع الحقول المطلوبة",
    "msg.fillSenderRequired": "يرجى ملء جميع حقول المرسل المطلوبة",
    "msg.selectSenderLocation": "يرجى اختيار موقع المرسل",
    "msg.fillCompanyName": "يرجى ملء اسم الشركة",
    "msg.fillReceiverRequired":
      "يرجى ملء جميع حقول المستقبل رقم {number} المطلوبة",
    "msg.selectReceiverLocation": "يرجى اختيار موقع المستقبل رقم {number}",
    "msg.fillPackageDetails": "يرجى ملء تفاصيل الطرد",
    "msg.invalidWeight": "يرجى إدخال وزن صحيح (1 كيلوغرام أو أكثر)",
    "msg.invalidLength": "يرجى إدخال طول صحيح (1 سم أو أكثر)",
    "msg.invalidWidth": "يرجى إدخال عرض صحيح (1 سم أو أكثر)",
    "msg.invalidHeight": "يرجى إدخال ارتفاع صحيح (1 سم أو أكثر)",
    "msg.invalidValue": "يرجى إدخال قيمة صحيحة للطرد",
    "msg.selectCompany": "يرجى اختيار شركة الشحن",
    "msg.selectPaymentMethod": "يرجى اختيار طريقة الدفع",
    "msg.insufficientBalance":
      "رصيد غير كافي. الرصيد المتاح: {balance} {currency}",
    "msg.fillCompanyInfo": "يرجى ملء معلومات الشركة للتجار",
    "msg.locationSelected": "تم اختيار الموقع بنجاح",
    "msg.operationSuccess": "تمت العملية بنجاح",
    "msg.operationFailed": "فشلت العملية",
    "msg.filesUploaded": "تم رفع {count} ملف بنجاح",
    "msg.shipmentCreatedMultiple": "تم إنشاء {count} شحنة بنجاح",
    "msg.profileSaved": "تم حفظ الملف الشخصي بنجاح",
    "msg.languageChanged": "تم تغيير اللغة بنجاح",

    // Form placeholders and labels
    "form.enterFirstName": "أدخل الاسم الأول",
    "form.enterLastName": "أدخل الاسم الأخير",
    "form.enterEmail": "أدخل البريد الإلكتروني",
    "form.enterPhone": "أدخل رقم الهاتف",
    "form.enterPassword": "أدخل كلمة المرور",
    "form.reenterPassword": "أعد إدخال كلمة المرور",
    "form.enterCompanyName": "أدخل اسم الشركة",
    "form.enterCommercialRegister": "أدخل رقم السجل التجاري",
    "form.selectAccountType": "اختر نوع الحساب",
    "form.selectCountry": "اختر البلد",
    "form.selectProvince": "اختر المحافظة",
    "form.selectCity": "اختر المدينة",
    "form.enterStreet": "أدخل الشارع",
    "form.searchCountries": "البحث في البلدان...",

    // Validation messages
    "validation.firstNameRequired": "الاسم الأول مطلوب",
    "validation.lastNameRequired": "الاسم الأخير مطلوب",
    "validation.emailRequired": "البريد الإلكتروني مطلوب",
    "validation.emailInvalid": "البريد الإلكتروني غير صحيح",
    "validation.phoneRequired": "رقم الهاتف مطلوب",
    "validation.passwordRequired": "كلمة المرور مطلوبة",
    "validation.passwordMinLength": "كلمة المرور يجب أن تكون 8 أحرف على الأقل",
    "validation.passwordsNotMatch": "كلمات المرور غير متطابقة",
    "validation.passwordMismatch": "كلمات المرور غير متطابقة",
    "validation.companyNameRequired": "اسم الشركة مطلوب",
    "validation.commercialRegisterRequired": "رقم السجل التجاري مطلوب",
    "validation.countryRequired": "البلد مطلوب",
    "validation.provinceRequired": "المحافظة مطلوبة",
    "validation.accountTypeRequired": "نوع الحساب مطلوب الرجاء الاختيار",
    "validation.cityRequired": "المدينة مطلوبة",
    "validation.streetRequired": "الشارع مطلوب",
    "validation.termsRequired": "يجب الموافقة على الشروط والأحكام",
  },
  en: {
    // App
    "app.name": "شحنلي",
    "app.welcome": "Welcome to شحنلي",
    "app.subtitle": "Smart Shipping Platform for Everyone",

    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.createShipment": "Create Shipment",
    "nav.shipments": "Shipments",
    "nav.contacts": "Senders/Receivers",
    "nav.balance": "Balance",
    "nav.reports": "Reports",
    "nav.settings": "Settings",
    "nav.logout": "Logout",
    "nav.profile": "Profile",

    // Auth
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.createNewAccount": "Create New Account",
    "auth.createAccount": "Create Account",
    "auth.backToLogin": "Back to Login",
    "auth.joinPlatform": "Join شحنلي platform today",
    "auth.email": "Email",
    "auth.emailAddress": "Email Address",
    "auth.password": "Password",
    "auth.confirmPassword": "Confirm Password",
    "auth.firstName": "First Name",
    "auth.lastName": "Last Name",
    "auth.phone": "Phone Number",
    "auth.phoneNumber": "Phone Number",
    "auth.accountType": "Account Type",
    "auth.individual": "Individual",
    "auth.merchant": "Merchant",
    "auth.companyName": "Company Name",
    "auth.commercialRegister": "Commercial Register",
    "auth.country": "Country",
    "auth.province": "Province",
    "auth.city": "City",
    "auth.street": "Street",
    "auth.rememberMe": "Remember me",
    "auth.forgotPassword": "Forgot password?",
    "auth.dontHaveAccount": "Don't have an account?",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.noAccount": "Don't have an account?",
    "auth.signInHere": "Sign in here",
    "auth.signUpHere": "Sign up here",
    "auth.welcome": "Welcome",
    "auth.signInSubtitle": "Sign in to access your account",
    "auth.signUpSubtitle": "Create a new account to get started",
    "auth.creatingAccount": "Creating account...",
    "auth.signingIn": "Signing in...",
    "auth.loginSuccess": "Login successful",
    "auth.loginError": "Login failed",
    "auth.logoutSuccess": "Logout successful",

    // Forgot Password - English translations
    "auth.resetPassword": "Reset Password",
    "auth.linkSent": "Link Sent",
    "auth.enterEmail": "Please enter your email",
    "auth.enterEmailForReset": "Enter your email to reset your password",
    "auth.checkEmailInstructions":
      "Check your email and follow the instructions to reset your password",
    "auth.sendResetLink": "Send Reset Link",
    "auth.sending": "Sending...",
    "auth.resetLinkSent": "Reset link sent",
    "auth.resetLinkSentTo": "Password reset link has been sent to:",
    "auth.didntReceiveEmail": "Didn't receive the email?",
    "auth.sendAgain": "Send Again",
    "auth.sendingResetLink": "Sending reset link...",
    "auth.linkSentSuccess": "Link sent successfully",
    "auth.linkSendFailed": "Failed to send link",
    "auth.resetPasswordError": "Password reset error occurred",

    // Profile
    "profile.title": "Profile",
    "profile.personalInfo": "Personal Information",
    "profile.fullName": "Full Name",
    "profile.company": "Company",
    "profile.website": "Website",
    "profile.bio": "Bio",
    "profile.memberSince": "Member since",
    "profile.saveChanges": "Save Changes",
    "profile.profileSaved": "Profile saved successfully",
    "profile.languageChanged": "Language changed successfully",
    "profile.accountTypeChanged": "Account type changed successfully",

    // Profile - Enhanced Account Type
    "profile.selectAccountTypeDesc":
      "Choose the account type that suits your usage",
    "profile.individualDesc": "For personal use and individuals",
    "profile.merchantDesc": "For companies and merchants",
    "profile.personalAccount": "Personal Account",
    "profile.verified": "Verified",
    "profile.easySetup": "Easy Setup",
    "profile.quickStart": "Quick Start",
    "profile.businessFeatures": "Business Features",
    "profile.bulkShipping": "Bulk Shipping",

    // Profile - Notifications
    "profile.notifications": "Notifications",
    "profile.emailNotifications": "Email Notifications",
    "profile.emailNotificationsDesc": "Receive notifications via email",
    "profile.smsNotifications": "SMS Notifications",
    "profile.smsNotificationsDesc": "Receive notifications via SMS",
    "profile.pushNotifications": "Push Notifications",
    "profile.pushNotificationsDesc": "Receive push notifications in browser",
    "profile.shipmentUpdates": "Shipment Updates",
    "profile.shipmentUpdatesDesc":
      "Receive notifications about shipment updates",
    "profile.promotions": "Promotions",
    "profile.promotionsDesc":
      "Receive notifications about offers and discounts",

    // Profile - Security
    "profile.security": "Security",
    "profile.twoFactorAuth": "Two-Factor Authentication",
    "profile.twoFactorAuthDesc":
      "Enable two-factor authentication for extra security",
    "profile.loginAlerts": "Login Alerts",
    "profile.loginAlertsDesc": "Receive alerts when new login occurs",
    "profile.sessionTimeout": "Session Timeout",
    "profile.timeout15": "15 minutes",
    "profile.timeout30": "30 minutes",
    "profile.timeout60": "60 minutes",
    "profile.timeout120": "120 minutes",
    "profile.changePassword": "Change Password",
    "profile.currentPassword": "Current Password",
    "profile.newPassword": "New Password",
    "profile.confirmNewPassword": "Confirm New Password",
    "profile.updatePassword": "Update Password",

    // Profile - Preferences
    "profile.preferences": "Preferences",
    "profile.language": "Language",
    "profile.currency": "Currency",
    "profile.dangerZone": "Danger Zone",
    "profile.deleteAccount": "Delete Account",

    // Features
    "features.easyManagement": "Easy shipment management",
    "features.realTimeTracking": "Real-time package tracking",
    "features.multiLanguage": "Multi-language support",

    // Terms
    "terms.agreeToTerms": "I agree to the",
    "terms.termsAndConditions": "Terms and Conditions",
    "terms.and": "and",
    "terms.privacyPolicy": "Privacy Policy",

    // Dashboard
    "dashboard.welcome": "Welcome",
    "dashboard.totalShipments": "Total Shipments",
    "dashboard.pendingShipments": "Pending Shipments",
    "dashboard.deliveredShipments": "Delivered Shipments",
    "dashboard.totalRevenue": "Total Revenue",
    "dashboard.recentShipments": "Recent Shipments",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.createShipment": "Create Shipment",
    "dashboard.viewAllShipments": "View All Shipments",
    "dashboard.manageContacts": "Manage Senders/Receivers",
    "dashboard.viewReports": "View Reports",
    "dashboard.viewAll": "View All",
    "dashboard.noShipments": "No Shipments",
    "dashboard.noShipmentsDesc": "You haven't created any shipments yet",
    "dashboard.walletBalance": "Wallet Balance",
    "dashboard.chargeWallet": "Charge Wallet",
    "dashboard.totalShipmentsCount": "Total Shipments",
    "dashboard.pendingCount": "Pending Shipments",
    "dashboard.deliveredCount": "Delivered Shipments",
    "dashboard.monthlyGrowth": "monthly growth",
    "dashboard.recentShipmentsTitle": "Recent Shipments",
    "dashboard.quickActionsTitle": "Quick Actions",
    "dashboard.createNewShipment": "Create New Shipment",
    "dashboard.startNewShipment": "Start a new shipment now",
    "dashboard.viewAllShipmentsDesc": "Track and manage all your shipments",
    "dashboard.sendersReceivers": "Manage Senders/Receivers",

    // Shipments
    "shipments.title": "Shipments",
    "shipments.subtitle": "Manage and track all your shipments",
    "shipments.createShipment": "Create Shipment",
    "shipments.searchShipments": "Search shipments...",
    "shipments.searchPlaceholder":
      "Search by tracking number, sender or receiver name...",
    "shipments.filterByStatus": "Filter by status",
    "shipments.allStatuses": "All Statuses",
    "shipments.pending": "Pending",
    "shipments.inTransit": "In Transit",
    "shipments.delivered": "Delivered",
    "shipments.cancelled": "Cancelled",
    "shipments.returned": "Returned",
    "shipments.noShipments": "No Shipments",
    "shipments.noShipmentsFound": "No shipments match your search criteria",
    "shipments.noMatchingShipments": "No shipments match your search criteria",
    "shipments.trackingNumber": "Tracking Number",
    "shipments.sender": "Sender",
    "shipments.receiver": "Receiver",
    "shipments.status": "Status",
    "shipments.amount": "Amount",
    "shipments.date": "Date",
    "shipments.actions": "Actions",
    "shipments.view": "View",
    "shipments.edit": "Edit",
    "shipments.track": "Track",
    "shipments.delete": "Delete",
    "shipments.details": "Shipment Details",
    "shipments.shipmentDetails": "Shipment Details",
    "shipments.close": "Close",
    "shipments.fromTo": "From {from} to {to}",
    "shipments.printBill": "Print Bill",
    "shipments.printShippingBill": "Print Shipping Bill",
    "shipments.shippingBill": "Shipping Bill",
    "shipments.choosePrintMethod": "Choose print method",
    "shipments.downloadPDF": "Download PDF",
    "shipments.printWindowOpened": "Print window opened",
    "shipments.pdfFeatureComingSoon": "PDF download feature coming soon",
    "shipments.cancelShipment": "Cancel Shipment",
    "shipments.cancelRequest": "Cancel Shipment Request",
    "shipments.confirmCancel": "Are you sure you want to cancel this shipment?",
    "shipments.cancelWarning":
      "This action cannot be undone. The shipment will be permanently cancelled.",
    "shipments.cancelReason": "Cancellation Reason",
    "shipments.cancelReasonPlaceholder":
      "Please explain why you want to cancel this shipment...",
    "shipments.enterCancelReason": "Please enter a cancellation reason",
    "shipments.goBack": "Go Back",
    "shipments.confirmCancelButton": "Confirm Cancellation",
    "shipments.cancelRequestSent":
      "Cancellation request sent for shipment {trackingNumber}",
    "shipments.cannotCancelApproved": "Cannot cancel approved shipments",
    "shipments.createdDate": "Created Date",
    "shipments.estimatedDelivery": "Estimated Delivery",

    // Status translations
    "status.pending": "Pending",
    "status.in-transit": "In Transit",
    "status.delivered": "Delivered",
    "status.cancelled": "Cancelled",
    "status.returned": "Returned",

    // Create Shipment
    "createShipment.title": "Create New Shipment",
    "createShipment.subtitle":
      "Fill in the details below to create a new shipment",
    "createShipment.senderInfo": "Sender Information",
    "createShipment.receiverInfo": "Receiver Information",
    "createShipment.shipmentDetails": "Shipment Details",
    "createShipment.pricing": "Pricing",
    "createShipment.selectFromContacts": "Select from Senders/Receivers",
    "createShipment.addNewContact": "Add New Client",
    "createShipment.selectContact": "Select Client",
    "createShipment.searchContacts": "Search senders/receivers...",
    "createShipment.noContacts": "No senders/receivers found",
    "createShipment.createShipment": "Create Shipment",
    "createShipment.success": "Shipment created successfully",
    "createShipment.error": "Failed to create shipment",

    // Shipment Creation Steps
    "shipment.title": "Create New Shipment",
    "shipment.step1.title": "Shipping Type",
    "shipment.step5.title": "Shipping & Payment",
    "shipment.reviewTitle": "Review Shipment",
    "shipment.selectShippingType": "Select Shipping Type",
    "shipment.selectShippingTypeDesc":
      "Choose whether this is a local or international shipment",
    "shipment.local": "Local Shipping",
    "shipment.localDesc": "Shipping within Syria only",
    "shipment.international": "International Shipping",
    "shipment.internationalDesc": "Shipping to other countries",
    "shipment.companiesAvailable": "companies available",
    "shipment.localOnly": "Local shipping only",
    "shipment.shippingCompany": "Shipping Company",
    "shipment.supportsAllCountries": "Supports all selected countries",
    "shipment.paymentMethod": "Payment Method",
    "shipment.wallet": "Wallet",
    "shipment.cashOnDelivery": "Cash on Delivery",
    "shipment.cod": "Cash on Delivery",
    "shipment.additionalNotes": "Additional Notes",
    "shipment.enterNotes": "Enter any additional notes...",
    "shipment.totalCostFor": "Total cost for {count} recipients",
    "shipment.totalCost": "Total Cost",
    "shipment.reviewDetails": "Review Shipment Details",
    "shipment.reviewDesc":
      "Please review all information before creating the shipment",
    "shipment.shippingInfo": "Shipping Information",
    "shipment.shippingType": "Shipping Type",
    "shipment.costSummary": "Cost Summary",
    "shipment.confirmCreate": "Confirm Create Shipment",
    "shipment.previous": "Previous",
    "shipment.next": "Next",
    "shipment.reviewShipment": "Review Shipment",
    "shipment.create": "Create Shipment",
    "shipment.creating": "Creating shipment...",
    "shipment.createSuccess": "Shipment created successfully",
    "shipment.createError": "Failed to create shipment",
    "shipment.notes": "Notes",

    // Contacts
    "contacts.title": "Senders/Receivers",
    "contacts.subtitle": "Manage your senders and receivers",
    "contacts.addContact": "Add Client",
    "contacts.searchContacts": "Search senders/receivers...",
    "contacts.filterByType": "Filter by type",
    "contacts.allTypes": "All Types",
    "contacts.sender": "Sender",
    "contacts.receiver": "Receiver",
    "contacts.both": "Both",
    "contacts.type": "Type",
    "contacts.contact": "Client",
    "contacts.noContacts": "No Senders/Receivers",
    "contacts.noMatchingContacts": "No senders/receivers match your search",
    "contacts.addContactDesc": "Add a new Client to use in shipments",
    "contacts.editContact": "Edit Client",
    "contacts.editContactDesc": "Edit Client information",
    "contacts.deleteSuccess": "Client deleted successfully",
    "contacts.addSuccess": "Client added successfully",
    "contacts.updateSuccess": "Client updated successfully",
    "contacts.locationSet": "Location set",

    // Client Types
    "client.type": "Client Type",
    "client.individual": "Individual",
    "client.merchant": "Merchant",
    "client.filterByType": "Filter by client type",
    "client.allTypes": "All Types",

    // Company
    "company.name": "Company Name",
    "company.enterName": "Enter company name",
    "company.documents": "Company Documents",
    "company.uploadDocuments": "Upload Company Documents",
    "company.documentsDesc": "PDF, JPG, PNG, DOC, DOCX - Max 5MB per file",
    "company.chooseFiles": "Choose Files",
    "company.uploadedFiles": "Uploaded Files",
    "company.filesUploaded": "files uploaded",

    // Balance
    "balance.title": "Balance",
    "balance.subtitle": "Manage your wallet balance and transaction history",
    "balance.usdBalance": "USD Balance",
    "balance.sypBalance": "SYP Balance",
    "balance.availableBalance": "Available Balance",
    "balance.chargeWallet": "Charge Wallet",
    "balance.amount": "Amount",
    "balance.currency": "Currency",
    "balance.paymentMethod": "Payment Method",
    "balance.bankTransfer": "Bank Transfer",
    "balance.bankTransferDesc": "Transfer from your bank account",
    "balance.shamCash": "Sham Cash",
    "balance.shamCashDesc": "Pay via Sham Cash",
    "balance.syriatelCash": "Syriatel Cash",
    "balance.syriatelCashDesc": "Pay via Syriatel Cash",
    "balance.mtnCash": "MTN Cash",
    "balance.mtnCashDesc": "Pay via MTN Cash",
    "balance.transferReason": "Transfer Reason",
    "balance.transferReasonPlaceholder":
      "Optional - reason for charging wallet",
    "balance.chargeNow": "Charge Now",
    "balance.transactionHistory": "Transaction History",
    "balance.completed": "Completed",
    "balance.pending": "Pending",
    "balance.enterValidAmount": "Please enter a valid amount",
    "balance.chargeSuccess":
      "Wallet charged successfully with {amount} {currency}",
    "balance.chargeError": "Failed to charge wallet",
    "balance.charging": "Charging wallet...",

    // Balance Search and Filter
    "balance.searchTransactions": "Search transactions...",
    "balance.searchPlaceholder":
      "Search by amount, payment method, or description...",
    "balance.filterByType": "Filter by type",
    "balance.allTypes": "All Types",
    "balance.charge": "Charge",
    "balance.withdraw": "Withdraw",
    "balance.payment": "Payment",
    "balance.filterByCurrency": "Filter by currency",
    "balance.allCurrencies": "All Currencies",
    "balance.filterByStatus": "Filter by status",
    "balance.allStatuses": "All Statuses",
    "balance.noTransactionsFound": "No transactions match your search",
    "balance.clearFilters": "Clear Filters",

    // Withdraw Balance
    "balance.withdrawBalance": "Withdraw Balance",
    "balance.withdrawBalanceDesc":
      "Request withdrawal of your balance from delivered COD shipments",
    "balance.availableForWithdraw": "Available for Withdrawal",
    "balance.availableFromCOD": "Available from COD Shipments",
    "balance.requestWithdraw": "Request Withdrawal",
    "balance.withdrawAmount": "Withdrawal Amount",
    "balance.withdrawMethod": "Withdrawal Method",
    "balance.accountDetails": "Account Details",
    "balance.bankAccountPlaceholder": "Bank account number or IBAN",
    "balance.mobileNumberPlaceholder": "Mobile phone number",
    "balance.notes": "Notes",
    "balance.withdrawNotesPlaceholder": "Additional notes (optional)",
    "balance.submitRequest": "Submit Request",
    "balance.withdrawRequests": "Withdrawal Requests",
    "balance.noWithdrawRequests": "No withdrawal requests",
    "balance.withdrawPending": "Pending",
    "balance.withdrawApproved": "Approved",
    "balance.withdrawRejected": "Rejected",
    "balance.withdrawCompleted": "Completed",
    "balance.requestDate": "Request Date",
    "balance.processedDate": "Processed Date",
    "balance.withdrawRequestDesc":
      "You can withdraw your balance from successfully delivered COD shipments",
    "balance.withdrawAmountExceeds":
      "Requested amount exceeds available withdrawal balance",
    "balance.enterAccountDetails": "Please enter account details",
    "balance.withdrawRequestSuccess":
      "Withdrawal request submitted successfully",
    "balance.withdrawError": "Failed to submit withdrawal request",
    "balance.submittingRequest": "Submitting request...",
    withdrawal: " Withdrawal",

    // Additional Balance translations
    "balance.wallet": "Wallet",
    "balance.walletCharge": "Wallet Charge",
    "balance.shipmentPayment": "Shipment Payment {shipmentId}",
    "balance.withdrawFromCOD": "Withdrawal request from COD shipments",
    "balance.withdrawFromCODShipments": "Balance withdrawal from COD shipments",
    "balance.bankAccountMasked": "Bank Account: ****1234",
    "balance.mobileNumberMasked": "Mobile: +963991234567",
    deposit: "Deposit",
    withdraw: "Withdraw",
    depositFunds: "Deposit Funds",
    withdrawFunds: "Withdraw Funds",
    depositDescription: "Deposit money into your account to use for recharging",
    withdrawDescription:
      "Withdraw money from your account to your preferred payment method",
    currency: "Currency",
    amount: "Amount",
    paymentMethod: "Payment Method",
    withdrawMethod: "Withdraw Method",
    selectPaymentMethod: "Select payment method",
    selectWithdrawMethod: "Select withdraw method",
    confirmDeposit: "Confirm Deposit",
    confirmWithdraw: "Confirm Withdraw",
    cancel: "Cancel",
    localBalance: "Local Balance",
    internationalBalance: "International Balance",
    syrianPoundForLocalRecharge: "Syrian Pound - For local recharge",
    usDollarForInternationalRecharge: "US Dollar - For international recharge",
    syrianPoundSymbol: "SYP",
    dollarSymbol: "$",
    syrianPoundWithCode: "Syrian Pound (SYP)",
    usDollarWithCode: "US Dollar (USD)",
    pleaseEnterValidAmount: "Please enter a valid amount",
    pleaseSelectPaymentMethod: "Please select a payment method",
    pleaseSelectWithdrawMethod: "Please select a withdraw method",
    minimumDepositAmount: "Minimum deposit amount",
    maximumDepositAmount: "Maximum deposit amount",
    minimumWithdrawAmount: "Minimum withdraw amount",
    insufficientBalance: "Insufficient balance",
    depositRequestSubmitted: "Deposit request submitted successfully",
    withdrawalRequestSubmitted: "Withdrawal request submitted successfully",
    creditCard: "Credit Card",
    bankTransfer: "Bank Transfer",
    mobileWallet: "Mobile Wallet",
    completed: "Completed",
    pending: "Pending",
    failed: "Failed",
    transactionHistory: "Transaction History",
    recentTransactions: "Recent Transactions",
    transactionsCount: "{{filtered}} of {{total}} transactions",
    searchTransactionsPlaceholder:
      "Search by reference, method, date, or amount...",
    transactionType: "Transaction Type",
    all: "All",
    syrianPound: "Syrian Pound",
    usDollar: "US Dollar",
    clearFilters: "Clear Filters",
    noMatchingTransactions: "No transactions match your search criteria",
    transactionDetails: "Transaction Details",
    type: "Type",
    status: "Status",
    method: "Method",
    date: "Date",
    reference: "Reference",
    notes: "Notes",
    optional: "Optional",
    withdrawNotesPlaceholder:
      "Any additional notes about the withdrawal (optional)",
    close: "Close",
    importantNotice: "Important Notice",
    balanceNotice:
      "Please note the difference between the two balances and how to use each:",
    localBalanceDescription:
      "Balance in Syrian Pound (SYP) is used for local recharge within Syria",
    internationalBalanceDescription:
      "Balance in US Dollar (USD) is used for international recharge",
    minimum: "Minimum",
    maximum: "Maximum",
    availableBalance: "Available Balance",
    urgentWithdrawalRequest: "Urgent withdrawal request",
    insufficientVerification: "Insufficient verification",

    // Client
    "sender.title": "Sender",
    "sender.name": "Name",
    "sender.phone": "Phone",
    "sender.email": "Email",
    "sender.country": "Country",
    "sender.state": "State",
    "sender.city": "City",
    "sender.street": "Street",
    "sender.address": "Address",
    "sender.detailedAddress": "Detailed Address",
    "sender.enterName": "Enter name",
    "sender.enterPhone": "Enter phone number",
    "sender.enterEmail": "Enter email",
    "sender.enterStreet": "Enter street address",
    "sender.enterDetailedAddress": "Enter detailed address",
    "sender.selectLocationOnMap": "Select Location on Map",
    "sender.clickToSelectLocation": "Click to select location for",
    "sender.interactiveMap": "Interactive Map",
    "sender.clickToSelect": "Click on the map to select location",
    "sender.selectThisLocation": "Select This Location",
    "sender.locationSelected": "Location selected",
    "sender.selectFromContacts": "Select from Senders/Receivers",
    "sender.selectOrEnterNew": "Select from senders/receivers or enter new",

    // Receiver
    "receiver.title": "Receiver",
    "receiver.titlePlural": "Receivers",
    "receiver.number": "Receiver #{number}",
    "receiver.count": "Number of Receivers",
    "receiver.enterName": "Enter receiver name",
    "receiver.enterDetailedAddress": "Enter receiver detailed address",
    "receiver.selectOrEnterNew": "Select from senders/receivers or enter new",
    "receiver.locationSelected": "Receiver location selected",

    // Package
    "package.title": "Package",
    "package.type": "Package Type",
    "package.selectType": "Select package type",
    "package.documents": "Documents",
    "package.electronics": "Electronics",
    "package.clothing": "Clothing",
    "package.books": "Books",
    "package.gifts": "Gifts",
    "package.food": "Food",
    "package.other": "Other",
    "package.weight": "Weight",
    "package.length": "Length",
    "package.width": "Width",
    "package.height": "Height",
    "package.dimensions": "Dimensions",
    "package.description": "Content Description",
    "package.enterDescription": "Enter package content description",
    "package.value": "Package Value",
    "package.fragile": "Fragile",

    // Payment
    "payment.cod.desc": "Payment will be collected upon delivery",

    // Currency
    "currency.usd": "US Dollar",
    "currency.syp": "Syrian Pound",
    "currency.selectCurrency": "Select Currency",

    // Countries
    "common.syria": "Syria",
    "common.sy": "Syria",
    "common.lb": "Lebanon",
    "common.jo": "Jordan",

    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.view": "View",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.actions": "Actions",
    "common.status": "Status",
    "common.date": "Date",
    "common.amount": "Amount",
    "common.total": "Total",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.warning": "Warning",
    "common.info": "Info",
    "common.confirm": "Confirm",
    "common.yes": "Yes",
    "common.no": "No",
    "common.close": "Close",
    "common.selectCountry": "Select Country",
    "common.selectState": "Select State",
    "common.selectCity": "Select City",
    "common.noResults": "No results found",
    "common.required": "*",
    "common.optional": "optional",
    "common.addReceiver": "Add Receiver",
    "common.confirmDeleteContact": "Are you sure you want to delete the client",
    "common.cannotReverseAction": "This action cannot be reversed.",

    // Messages
    "msg.fillRequired": "Please fill in all required fields",
    "msg.fillSenderRequired": "Please fill in all required sender fields",
    "msg.selectSenderLocation": "Please select sender location",
    "msg.fillCompanyName": "Please fill in company name",
    "msg.fillReceiverRequired":
      "Please fill in all required fields for receiver #{number}",
    "msg.selectReceiverLocation":
      "Please select location for receiver #{number}",
    "msg.fillPackageDetails": "Please fill in package details",
    "msg.invalidWeight": "Please enter a valid weight (1 kg or more)",
    "msg.invalidLength": "Please enter a valid length (1 cm or more)",
    "msg.invalidWidth": "Please enter a valid width (1 cm or more)",
    "msg.invalidHeight": "Please enter a valid height (1 cm or more)",
    "msg.invalidValue": "Please enter a valid package value",
    "msg.selectCompany": "Please select a shipping company",
    "msg.selectPaymentMethod": "Please select a payment method",
    "msg.insufficientBalance":
      "Insufficient balance. Available: {balance} {currency}",
    "msg.fillCompanyInfo": "Please fill in company information for merchants",
    "msg.locationSelected": "Location selected successfully",
    "msg.operationSuccess": "Operation completed successfully",
    "msg.operationFailed": "Operation failed",
    "msg.filesUploaded": "{count} files uploaded successfully",
    "msg.shipmentCreatedMultiple": "{count} shipments created successfully",
    "msg.profileSaved": "Profile saved successfully",
    "msg.languageChanged": "Language changed successfully",

    // Form placeholders and labels
    "form.enterFirstName": "Enter first name",
    "form.enterLastName": "Enter last name",
    "form.enterEmail": "Enter email address",
    "form.enterPhone": "Enter phone number",
    "form.enterPassword": "Enter password",
    "form.reenterPassword": "Re-enter password",
    "form.enterCompanyName": "Enter company name",
    "form.enterCommercialRegister": "Enter commercial register number",
    "form.selectAccountType": "Select account type",
    "form.selectCountry": "Select country",
    "form.selectProvince": "Select province",
    "form.selectCity": "Select city",
    "form.enterStreet": "Enter street address",
    "form.searchCountries": "Search countries...",

    // Validation messages
    "validation.firstNameRequired": "First name is required",
    "validation.lastNameRequired": "Last name is required",
    "validation.emailRequired": "Email is required",
    "validation.emailInvalid": "Email is invalid",
    "validation.phoneRequired": "Phone number is required",
    "validation.passwordRequired": "Password is required",
    "validation.passwordMinLength": "Password must be at least 8 characters",
    "validation.passwordsNotMatch": "Passwords do not match",
    "validation.passwordMismatch": "Passwords do not match",
    "validation.companyNameRequired": "Company name is required",
    "validation.commercialRegisterRequired":
      "Commercial register number is required",
    "validation.countryRequired": "Country is required",
    "validation.provinceRequired": "Province is required",
    "validation.accountTypeRequired": "Account type required, please select",
    "validation.cityRequired": "City is required",
    "validation.streetRequired": "Street address is required",
    "validation.termsRequired": "You must agree to the terms and conditions",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguage] = useState<Language>("ar");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language;
    if (savedLanguage && (savedLanguage === "ar" || savedLanguage === "en")) {
      setLanguage(savedLanguage);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.setAttribute("lang", language);
    document.documentElement.setAttribute(
      "dir",
      language === "ar" ? "rtl" : "ltr"
    );
  }, [language]);

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation =
      translations[language][key] || translations["en"][key] || key;

    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        translation = translation.replace(`{${paramKey}}`, String(paramValue));
      });
    }

    return translation;
  };

  const isRTL = language === "ar";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
